### ISSUE TITLE
null setting issues

### ISSUE THREAD

**Issue by YTiceice** [academiadocodigo/SimpleORM#49]
[08:33:45] [Server thread/WARN]: Nag author(s): '[caoli5288@gmail.com]' of 'PlayerSQL' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[08:33:45] [Server thread/INFO]: [PlayerSQL] ORM lib load okay!
[08:33:46] [Server thread/ERROR]: [com.avaje.ebean.config.PropertyMapLoader] ebean.properties not found
[08:33:46] [Server thread/INFO]: [com.avaje.ebeaninternal.api.ClassLoadContext] Ambiguous ClassLoader choice preferContext:true Context:org.bukkit.plugin.java.PluginClassLoader Caller:org.bukkit.plugin.java.PluginClassLoader
[08:33:46] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] PlayerSQL@48188640-4978-46c1-b96e-47d05f0672b7 - Starting...
[08:33:47] [Server thread/ERROR]: [com.zaxxer.hikari.pool.HikariPool] PlayerSQL@48188640-4978-46c1-b96e-47d05f0672b7 - Exception during pool initialization.
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[patched_1.17.1.jar:git-Paper-325]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[patched_1.17.1.jar:git-Paper-325]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833) ~[patched_1.17.1.jar:git-Paper-325]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[patched_1.17.1.jar:git-Paper-325]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[patched_1.17.1.jar:git-Paper-325]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[patched_1.17.1.jar:git-Paper-325]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[SimpleORM.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[SimpleORM.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[SimpleORM.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[SimpleORM.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[SimpleORM.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[SimpleORM.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[SimpleORM.jar:?]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.checkDataSource(DefaultServerFactory.java:472) ~[SimpleORM.jar:?]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:170) ~[SimpleORM.jar:?]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:63) ~[SimpleORM.jar:?]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) ~[SimpleORM.jar:?]
	at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:270) ~[SimpleORM.jar:?]
	at com.mengcraft.playersql.PluginMain.onEnable(PluginMain.java:92) ~[playersql.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-325]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-325]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:502) ~[patched_1.17.1.jar:git-Paper-325]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:544) ~[patched_1.17.1.jar:git-Paper-325]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:458) ~[patched_1.17.1.jar:git-Paper-325]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725) ~[patched_1.17.1.jar:git-Paper-325]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-325]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Paper-325]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-325]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
[08:33:47] [Server thread/ERROR]: Error occurred while enabling PlayerSQL v2.12.2 (Is it up to date?)
com.mengcraft.simpleorm.DatabaseException: javax.persistence.PersistenceException: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:272) ~[SimpleORM.jar:?]
	at com.mengcraft.playersql.PluginMain.onEnable(PluginMain.java:92) ~[playersql.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-325]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-325]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:502) ~[patched_1.17.1.jar:git-Paper-325]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:544) ~[patched_1.17.1.jar:git-Paper-325]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:458) ~[patched_1.17.1.jar:git-Paper-325]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725) ~[patched_1.17.1.jar:git-Paper-325]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-325]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Paper-325]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-325]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: javax.persistence.PersistenceException: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.checkDataSource(DefaultServerFactory.java:482) ~[SimpleORM.jar:?]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:170) ~[SimpleORM.jar:?]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:63) ~[SimpleORM.jar:?]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) ~[SimpleORM.jar:?]
	at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:270) ~[SimpleORM.jar:?]
	... 11 more
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[patched_1.17.1.jar:git-Paper-325]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[patched_1.17.1.jar:git-Paper-325]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833) ~[patched_1.17.1.jar:git-Paper-325]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[patched_1.17.1.jar:git-Paper-325]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[patched_1.17.1.jar:git-Paper-325]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[patched_1.17.1.jar:git-Paper-325]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[SimpleORM.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[SimpleORM.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[SimpleORM.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[SimpleORM.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[SimpleORM.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[SimpleORM.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[SimpleORM.jar:?]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.checkDataSource(DefaultServerFactory.java:472) ~[SimpleORM.jar:?]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:170) ~[SimpleORM.jar:?]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:63) ~[SimpleORM.jar:?]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) ~[SimpleORM.jar:?]
	at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:270) ~[SimpleORM.jar:?]
	... 11 more

**Comment by alepmedeiros** [comment]
by the message are you using simpleorm in java?
about the compatibility with null fields, it is getting an update, but we didn't get to work it with Java
